version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - ./:/counter_app
        links:
            - db:postgresql
        container_name: counterapp_web_1
        depends_on:
            - db
    db:
        image: postgres:10
        restart: always
        container_name: counterapp_db_1
        environment:
            POSTGRES_PASSWORD: rootpass
            POSTGRES_USER: root
            POSTGRES_DB: counter
